// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMks9AGga4mIQv45FGb2A7hw2zwxa0eTQ',
    appId: '1:692513783351:web:0a38e97eb286ceb78449b2',
    messagingSenderId: '692513783351',
    projectId: 'test-flutter-apps-6861f',
    authDomain: 'test-flutter-apps-6861f.firebaseapp.com',
    storageBucket: 'test-flutter-apps-6861f.appspot.com',
    measurementId: 'G-PRESK0B7SF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNIo9XLgW4DFi8Dc_DqvwxCYdfJXJQmgM',
    appId: '1:692513783351:android:b2dde7f6474081868449b2',
    messagingSenderId: '692513783351',
    projectId: 'test-flutter-apps-6861f',
    storageBucket: 'test-flutter-apps-6861f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5C6Dyp52m-6zvFbMAihLleV90RwQzNJo',
    appId: '1:692513783351:ios:7f6e30116d26f30a8449b2',
    messagingSenderId: '692513783351',
    projectId: 'test-flutter-apps-6861f',
    storageBucket: 'test-flutter-apps-6861f.appspot.com',
    iosBundleId: 'com.exampledomain.authFirebaseAppPernonalDesktop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5C6Dyp52m-6zvFbMAihLleV90RwQzNJo',
    appId: '1:692513783351:ios:7f6e30116d26f30a8449b2',
    messagingSenderId: '692513783351',
    projectId: 'test-flutter-apps-6861f',
    storageBucket: 'test-flutter-apps-6861f.appspot.com',
    iosBundleId: 'com.exampledomain.authFirebaseAppPernonalDesktop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCMks9AGga4mIQv45FGb2A7hw2zwxa0eTQ',
    appId: '1:692513783351:web:6e779c25b8c98b728449b2',
    messagingSenderId: '692513783351',
    projectId: 'test-flutter-apps-6861f',
    authDomain: 'test-flutter-apps-6861f.firebaseapp.com',
    storageBucket: 'test-flutter-apps-6861f.appspot.com',
    measurementId: 'G-Z4T0GCNZN1',
  );
}
